# Colle ici le contenu de ton .gitlab-ci.yml (le YAML que tu veux utiliser)
stages:
  - test

variables:
  NODE_ENV: test

cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
    - backend/node_modules/

.before_script:
  before_script:
    - cd backend
    - npm ci

.test_template: &npm_test
  stage: test
  image: node:20
  before_script:
    - cd backend
    - npm ci
  script:
    - npm run lint
    - npm test
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - backend/node_modules/

test:node20:
  <<: *npm_test
